if(NOT DEFINED PACKAGE_NAME)
  set(PACKAGE_NAME RPi)
endif()

if(NOT DEFINED PACKAGE_START_YEAR)
  set(PACKAGE_START_YEAR 2017)
endif()

set(PACKAGE_VERSION_MAJOR 0)
set(PACKAGE_VERSION_MINOR 0)
set(PACKAGE_VERSION_PATCH 0)
set(PACKAGE_VERSION_TWEAK 0)

if((NOT DEFINED FILE_VERSION_MAJOR) OR (NOT DEFINED FILE_VERSION_MINOR) OR (NOT
DEFINED FILE_VERSION_PATCH) OR (NOT DEFINED FILE_VERSION_TWEAK))
  set(FILE_VERSION_MAJOR ${PACKAGE_VERSION_MAJOR})
  set(FILE_VERSION_MINOR ${PACKAGE_VERSION_MINOR})
  set(FILE_VERSION_PATCH ${PACKAGE_VERSION_PATCH})
  set(FILE_VERSION_TWEAK ${PACKAGE_VERSION_TWEAK})
endif()
